// Generated by Website Factory. Update via the factory pipeline, not by hand.

export interface MenuItem {
  name: string;
  native?: string;
  nr?: string;
  description?: string;
  price: string;
  spicy?: boolean;
  vegan?: boolean;
  note?: string;
}

export type MenuCategory = {
  id: string;
  label: string;
  native?: string;
  intro?: string;
  items: MenuItem[];
};

export const menuDataGeneratedFromFactory = true;

export const menuImageUrls: string[] = [];

export const menuCategories: MenuCategory[] = [
  {
    "id": "speisekarte",
    "label": "Speisekarte",
    "items": [
      {
        "name": "1– von 10 Personen gemeldet",
        "description": "Preis pro Person:",
        "price": "10"
      },
      {
        "name": "1–",
        "price": "10"
      },
      {
        "name": "10–",
        "price": "20"
      },
      {
        "name": "20–",
        "price": "30"
      },
      {
        "name": "30–",
        "price": "40"
      }
    ]
  }
];
