// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "Süppchen Mannheim-Lindenhof",
  "shortName": "Süppchen Mannheim-Lindenhof",
  "tagline": "Bar",
  "logoGlyph": "S",
  "cuisine": "Bar",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "0176 90753076",
  "phoneLink": "tel:+4917690753076",
  "email": "",
  "address": {
    "street": "Meerfeldstraße 24",
    "cityLine": "68163 Mannheim",
    "city": "Mannheim"
  },
  "mapsUrl": "https://maps.google.com/?cid=4987599167989627520&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=4987599167989627520&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://www.instagram.com/heinrichs_mannheim/",
    "facebook": "https://www.facebook.com/p/Lindenhof-d%C3%B6ner-100057278815454",
    "tiktok": "https://tiktok.com/@suppchenmannheimlindenhof.mannheim",
    "hidden": {
      "instagram": false,
      "facebook": false,
      "tiktok": true
    },
    "titleHidden": false
  },
  "closedDays": [],
  "closedDaysLabel": "",
  "hours": [
    {
      "day": "Montag, Dienstag, Mittwoch, Donnerstag & Sonntag",
      "time": "10:00–01:00 Uhr",
      "closed": false
    },
    {
      "day": "Freitag & Samstag",
      "time": "10:00–03:00 Uhr",
      "closed": false
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "Süppchen Mannheim-Lindenhof | Bar in Mannheim",
    "description": "Süppchen Mannheim-Lindenhof in Mannheim. bar Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "keywords": [
      "Süppchen Mannheim-Lindenhof",
      "Bar Mannheim",
      "Süppchen Mannheim-Lindenhof Mannheim"
    ],
    "ogTitle": "Süppchen Mannheim-Lindenhof",
    "ogDescription": "Süppchen Mannheim-Lindenhof in Mannheim. bar Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "",
    "vatId": "",
    "responsiblePerson": ""
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
