// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.3,
  "totalRatings": 26,
  "reviews": [
    {
      "author": "Arno",
      "rating": 5,
      "text": "Das Süppchen verkörpert den Charme traditioneller Kneipen, in denen Geselligkeit und eine entspannte Atmosphäre im Vordergrund stehen. Hier kann man in angenehmer Runde bei Musik ein Getränk genießen, sich unterhalten und die Zeit miteinander verbringen, ohne dass es zu viel Schnickschnack gibt. Solche Orte bieten eine willkommene Abwechslung zum hektischen Alltag.",
      "time": "vor einem Jahr"
    },
    {
      "author": "Sören Messing",
      "rating": 5,
      "text": "Das Süppchen ist eine wunderschöne Kneipe im Lindenhof. Die Getränke sind lecker und das Ambiente immer einen Besuch wert. Das Personal ist so verführerisch, dass man Sie am Liebsten zum Kaffee eingeladen möchte.",
      "time": "vor einem Jahr"
    },
    {
      "author": "Chris Widdi",
      "rating": 5,
      "text": "Das „Süppchen“ – Eine Oase kulinarischer Hingabe, die zwischen Mainstream und Avantgarde oszilliert, bietet weit mehr als nur eine bloße Suppe. Doch der wahre kulturelle Höhepunkt dieses gastronomischen Gesamtkunstwerks verbirgt sich abseits der belebten Hauptattraktionen, in einem subtilen Intermezzo zwischen Schankraum und Toiletten: Ein Raum, der auf den ersten Blick unscheinbar erscheinen mag, beherbergt ein Artefakt von globaler Bedeutung – einen Tannenzapfen.\n\nDieser Tannenzapfen, nicht etwa das Produkt bloßer Dekorationslaune, sondern ein Symbol für die tief verwurzelte Beziehung zwischen Natur und Zivilisation, ragt erhaben aus seiner Existenz heraus. Weltweit einzigartig in seiner Form, seiner Textur und seiner metaphysischen Aura, zieht er den Betrachter in seinen Bann und zwingt ihn, über die vergängliche Natur der menschlichen Erfahrung zu sinnieren.\n\nEs wäre schlichtweg fahrlässig, Mannheim zu besuchen, ohne diesem Meisterwerk der botanischen Kunst die gebührende Aufmerksamkeit zu schenken. Inmitten von Konsum und Kloschlangen erhebt sich dieser Tannenzapfen wie eine stille Mahnung an die Größe des Unscheinbaren. Ein touristisches Highlight, das seinesgleichen sucht und zugleich die trivialen Freuden des Alltags transzendiert.\n\nWer das „Süppchen“ besucht und diesen Zapfen übersieht, hat in Wahrheit nichts gesehen.",
      "time": "vor einem Jahr"
    }
  ]
};
